name: K6 load test
on: [push]
jobs:
  build:
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: scripts/mock_api.js