name: Teste-de-Performance-K6
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: Teste-de-Performance-K6
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - run k6 load test
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: scripts/mock_api.js