name: K6 load test
on: [push]
jobs:
  build:
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - checkout
        uses: actions/checkout@v3

      - name: Step 2 - run k6 local test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: scripts/mock_api.js